version: '3'

services:
  mcserver:
    image: itzg/minecraft-server:java21-alpine
    container_name: mcserver
    environment:
      TYPE: PAPER
      MEMORY: 2G
      INIT_MEMORY: 2G
      MAX_MEMORY: 4G
      EULA: TRUE
      VERSION: 1.21.1
      JVM_OPTS: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
      DEBUG_EXEC: true
      ENABLE_COMMAND_BLOCK: true
    volumes:
      - ./server:/data
    ports:
      - "25565:25565"
      - "5005:5005"
      - "8123:8123"