version: '3'
services:
  mcserver:
    image: itzg/minecraft-server:java21-alpine
    container_name: mcserver
    environment:
      TYPE: PAPER
      MEMORYSIZE: 2G
      EULA: TRUE
      VERSION: 1.21
      JVM_OPTS: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
      DEBUG_EXEC: true
    volumes:
      - ./server:/data
    ports:
      - "25565:25565"
      - "5005:5005"
      - "8123:8123"