name: Feature request
description: "Suggest an idea for this project"
title: '[Feature request] '
labels: ["enhancement"]
body:
  - type: textarea
    attributes:
      label: Description
      description: Please describe the issue. You can include screenshot or video
    validations:
      required: true