name: Publish to Modrinth

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"
          cache: gradle

      - name: Make Gradle wrapper executable
        run: chmod +x ./gradlew

      - name: Extract version from Gradle
        id: version
        run: |
          VERSION=$(./gradlew properties -q | grep "^version:" | awk '{print $2}')
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "Extracted version: $VERSION"

      - name: Build plugin
        run: ./gradlew shadowJar --no-daemon

      - name: Publish to Modrinth
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          modrinth-id: KqTWR5Ji
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          version: ${{ steps.version.outputs.version }}
          version-type: release

          loaders: |
            bukkit
            paper
            spigot
            purpur
          game-versions: |
            1.18.x
            1.19.x
            1.20.x
            1.21.x
          files: |
            build/libs/CyanoFactions-*.jar
          retry-attempts: 2
          retry-delay: 10000
          fail-mode: fail
