name: Nightly GitHub Release

on:
  schedule:
    - cron: '0 0 * * *'  # Every day at midnight UTC
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle
      - name: Run the Gradle build for ImprovedFactions
        working-directory: ./improved-factions
        run: ./gradlew clean build

      - name: Extract version from build.gradle
        id: extract_version
        working-directory: ./improved-factions
        run: echo "VERSION=$(./gradlew -q printVersion)" >> $GITHUB_ENV

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.VERSION }}-nightly
          target_commitish: dev
          name: ${{ env.VERSION }}-nightly
          body: |
            Automated nightly release.
          draft: false
          prerelease: true
        env:
          GITHUB_TOKEN: ${{ secrets.GB_TOKEN }}

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.release.outputs.upload_url }}
          asset_path: improved-factions/build/libs/ImprovedFactions-*.jar
          asset_name: ImprovedFactions-${{ env.VERSION }}.jar
          asset_content_type: application/java-archive
