name: Nightly Build gradle

on:
  schedule:
    - cron: '0 0 * * *'  # Every day at midnight UTC
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

      - name: Ensure Gradle Wrapper is executable
        run: chmod +x ./improved-factions/gradlew

      - name: Build with Gradle Wrapper
        working-directory: ./improved-factions
        run: ./gradlew build

      - name: Extract version from build.gradle
        id: extract_version
        working-directory: ./improved-factions
        run: echo "VERSION=$(./gradlew -q properties | grep "^version:" | awk '{print $2}')" >> $GITHUB_ENV

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        id: release
        with:
          tag_name: ${{ env.VERSION }}-nightly
          target_commitish: dev
          name: ${{ env.VERSION }}-nightly
          body: |
            Automated nightly release.
          draft: false
          prerelease: true
          files: |
            ./improved-factions/build/libs/ImprovedFactions-${{ env.VERSION }}.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GB_TOKEN }}


  dependency-submission:

    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Ensure Gradle Wrapper is executable
        run: chmod +x ./improved-factions/gradlew

      # Generates and submits a dependency graph, enabling Dependabot Alerts for all project dependencies.
      # See: https://github.com/gradle/actions/blob/main/dependency-submission/README.md
      - name: Generate and submit dependency graph
        uses: gradle/actions/dependency-submission@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0
        with:
          build-root-directory: ./improved-factions
          build-scan-publish: true
          build-scan-terms-of-use-url: "https://gradle.com/help/legal-terms-of-use"
          build-scan-terms-of-use-agree: "yes"