name: Nightly GitHub Release

on:
  schedule:
    - cron: '0 0 * * *'  # Every day at midnight UTC

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Run the Maven build for ImprovedFactionsBase
        working-directory: ./improved-factions-base
        run: mvn clean package

      - name: Extract version from pom.xml
        id: extract_version
        working-directory: ./improved-factions-base
        run: echo "VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.VERSION }}-nightly
          target_commitish: dev
          name: ${{ env.VERSION }}-nightly
          body: |
            Automated nightly release.
          draft: false
          prerelease: true
        env:
          GITHUB_TOKEN: ${{ secrets.GB_TOKEN }}

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.release.outputs.upload_url }}
          asset_path: improved-factions-base/target/ImprovedFactions-*.jar
          asset_name: ImprovedFactions-${{ env.VERSION }}.jar
          asset_content_type: application/java-archive
